name: Slides build
on: push

jobs:
  build_index:
    runs-on: ubuntu-18.04
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - run: mkdir output
      # Just a test for example build.
      - uses: docker://pandoc/latex:latest
        with:
          args: -t revealjs -s test_slides.md -o output/test_slides.html -V theme=moon -V minScale=0.1 -V width='90%' -V height='90%'
      # Build index
      - uses: docker://pandoc/latex:latest
        with:
          args: -s -o output/index.html -f markdown index.md
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}
  build_slides:
    strategy:
      matrix:
        slides:
          - 00_Course_Introduction
          - 01_Introduction_Big_Data
    runs-on: ubuntu-18.04
    needs: [build_index]
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - run: mkdir output
      # Build slidedeck
      # TODO: Would need a index first...
      - uses: docker://pandoc/latex:latest
        with:
          args: -t revealjs -s ${{ matrix.slides }}.md -o output/${{ matrix.slides }}.html -V theme=solarized -V minScale=0.1 -V width='90%' -V height='90%'
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}
  deploy:
    runs-on: ubuntu-18.04
    needs: [build_slides]
    steps:
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
