name: Slides build
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      #Checkout our files
      - uses: actions/checkout@v2
      #Needs revealjs styles. Default for now.
      - uses: actions/checkout@v2
        with:
          repository: 'hakimel/reveal.js'
          path: 'reveal.js'
      - uses: docker://pandoc/latex:2.9
        with:
          args: pandoc -t revealjs -s test_slides.md -o output/test_slides.html
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
