name: Slides build
on: push

jobs:
  build_index:
    runs-on: ubuntu-18.04
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - run: mkdir output && cp -r images output/
      # Just a test for example build.
      - uses: docker://pandoc/latex:latest
        with:
          args: >- # allows you to break string into multiple lines
            -t revealjs -s src/test_slides.md -o output/test_slides.html
            -V theme=moon -V minScale=0.1 -V width='90%' -V height=900
      # Build index
      - uses: docker://pandoc/latex:latest
        with:
          args: -s -o output/index.html -f markdown src/index.md
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}-index
  build_slides:
    strategy:
      max-parallel: 1 # needed for the cache mechanism to work
      matrix:
        slides:
          - 00_Course_Introduction
          - 00_CNES_Short_Course_Introduction
          - 00_OBD_Course_Introduction
          - 01_Introduction_Big_Data
          - 02_Big_Data_Platforms
          - 03_Spark_Introduction
          - 10_Cloud_Computing
          - 11_ContainersAndDocker
          - 12_OrchestrationKubernetes
          - 13_Dask_On_Cloud
          - 14_ObjectStorage
          - 21_Python_Data_Processing
          - 22_Dask_Pangeo
          - 30_Evaluation
    runs-on: ubuntu-18.04
    needs: [build_index]
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - run: mkdir output
      # Build slidedeck
      - uses: docker://pandoc/latex:latest
        with:
          args: >- # allows you to break string into multiple lines
            -t revealjs -s src/${{ matrix.slides }}.md -o output/${{ matrix.slides }}.html
            -V theme=solarized -V minScale=0.1 -V width=1800 -V height=900
            -V background-image=images/background-logo.png
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}-${{ matrix.slides }}
          restore-keys: ${{ github.sha }}-
  build_slides_pdf:
    strategy:
      max-parallel: 1 # needed for the cache mechanism to work
      matrix:
        slides:
          - 00_Course_Introduction
          - 00_CNES_Short_Course_Introduction
          - 00_OBD_Course_Introduction
          - 01_Introduction_Big_Data
          - 02_Big_Data_Platforms
          - 03_Spark_Introduction
          - 10_Cloud_Computing
          - 11_ContainersAndDocker
          - 12_OrchestrationKubernetes
          - 13_Dask_On_Cloud
          - 14_ObjectStorage
          - 21_Python_Data_Processing
          - 22_Dask_Pangeo
          - 30_Evaluation
    runs-on: ubuntu-18.04
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - run: mkdir output_pdf && cp -r images output_pdf/
      # Build slidedeck
      - uses: docker://pandoc/latex:latest
        with:
          args: >- # allows you to break string into multiple lines
            -t beamer -s src/${{ matrix.slides }}.md -o output_pdf/${{ matrix.slides }}.pdf
            -V theme:Warsaw
      - uses: actions/cache@v2
        id: cache-pdf
        with:
          path: output_pdf/*
          key: pdf-${{ github.sha }}-${{ matrix.slides }}
          restore-keys: pdf-${{ github.sha }}-
  deploy:
    runs-on: ubuntu-18.04
    needs: [build_slides]
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-html
        with:
          path: output/*
          key: ${{ github.sha }}-deploy
          restore-keys: ${{ github.sha }}-
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
  deploy_pdf:
    runs-on: ubuntu-18.04
    needs: [build_slides_pdf]
    steps:
      # Checkout our files
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-pdf
        with:
          path: output_pdf/*
          key: pdf-${{ github.sha }}-deploy
          restore-keys: pdf-${{ github.sha }}-
      - uses: actions/upload-artifact@master
        with:
          name: output_pdf
          path: output_pdf
